import { Edit3, PackagePlus, Save, Trash2, X } from 'lucide-react'
import { useState } from 'react'

const blankProduct = { title: '', brand: '', category: 'Smartphones', price: '', rating: '4.5', stock: '10', image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=85', description: '' }
export default function Admin({ products, onSave, onDelete }) {
  const [form, setForm] = useState(blankProduct)
  const [editingId, setEditingId] = useState(null)
  const update = (event) => setForm({ ...form, [event.target.name]: event.target.value })
  const submit = (event) => { event.preventDefault(); onSave({ ...form, id: editingId || Date.now(), price: Number(form.price), rating: Number(form.rating), stock: Number(form.stock) }); setForm(blankProduct); setEditingId(null) }
  const edit = (product) => { setForm(product); setEditingId(product.id); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  return <main className="admin-page"><div className="container"><div className="admin-header"><div><p className="eyebrow">CONTROL ROOM</p><h1>Manage products.</h1></div><span className="admin-status">● Local catalog</span></div><div className="admin-layout"><form className="admin-form" onSubmit={submit}><div className="form-title"><span>{editingId ? 'Edit product' : 'Add a product'}</span>{editingId && <button type="button" onClick={() => { setEditingId(null); setForm(blankProduct) }}><X size={16} /></button>}</div>{['title', 'brand', 'price', 'stock', 'image', 'description'].map((field) => <label key={field}>{field}<input required={field !== 'description'} name={field} value={form[field]} onChange={update} type={['price', 'stock'].includes(field) ? 'number' : 'text'} /></label>)}<label>category<select name="category" value={form.category} onChange={update}><option>Smartphones</option><option>Laptops</option><option>Audio</option><option>Wearables</option><option>Gaming</option><option>Accessories</option><option>Tablets</option></select></label><label>rating<input name="rating" type="number" min="1" max="5" step=".1" value={form.rating} onChange={update} /></label><button className="button button-dark" type="submit">{editingId ? <><Save size={16} /> Save changes</> : <><PackagePlus size={16} /> Add product</>}</button></form><div className="admin-products"><div className="admin-list-heading"><strong>{products.length} products</strong><span>Last updated just now</span></div>{products.map((product) => <div className="admin-product" key={product.id}><img src={product.image} alt="" /><div><strong>{product.title}</strong><span>{product.brand} · ${product.price}</span></div><button onClick={() => edit(product)} aria-label={`Edit ${product.title}`}><Edit3 size={16} /></button><button onClick={() => onDelete(product.id)} aria-label={`Delete ${product.title}`}><Trash2 size={16} /></button></div>)}</div></div></div></main>
}