import { ArrowLeft, Minus, Plus, ShoppingBag, Trash2 } from 'lucide-react'
import { Link } from 'react-router-dom'

const fmt = (n) => n.toLocaleString('en-US')

export default function Cart({ cart, onUpdateQuantity, onRemove, onClear }) {
  const subtotal = cart.reduce((sum, item) => sum + item.price * item.quantity, 0)
  const shipping = subtotal >= 75 || subtotal === 0 ? 0 : 8
  return <main className="cart-page"><div className="container"><div className="page-heading"><div><p className="eyebrow">YOUR BAG</p><h1>Ready when you are.</h1></div><Link className="back-link" to="/products"><ArrowLeft size={15} /> Continue shopping</Link></div>{cart.length ? <div className="cart-layout"><div className="cart-items">{cart.map((item) => <div className="cart-item" key={item.id}><img src={item.image} alt={item.title} /><div className="cart-item-copy"><span>{item.brand} · {item.category}</span><h3>{item.title}</h3><strong>${fmt(item.price.toLocaleString('en-US'))}</strong></div><div className="quantity-control"><button onClick={() => onUpdateQuantity(item.id, -1)} aria-label="Decrease quantity"><Minus size={14} /></button><span>{item.quantity}</span><button onClick={() => onUpdateQuantity(item.id, 1)} aria-label="Increase quantity"><Plus size={14} /></button></div><button className="remove-button" onClick={() => onRemove(item.id)} aria-label={`Remove ${item.title}`}><Trash2 size={16} /></button></div>)}<button className="clear-button" onClick={onClear}>Clear cart</button></div><aside className="order-summary"><h2>Order summary</h2><div><span>Subtotal</span><strong>${fmt(subtotal)}</strong></div><div><span>Shipping</span><strong>{shipping ? `$${shipping}` : 'Free'}</strong></div><div className="summary-total"><span>Total</span><strong>${fmt(subtotal + shipping)}</strong></div><button className="button button-dark checkout-button">Checkout <ArrowLeft size={16} /></button><p>Taxes calculated at checkout.</p></aside></div> : <div className="empty-state"><ShoppingBag size={27} /><h2>Your bag is waiting.</h2><p>Add something good to get started.</p><Link className="button button-dark" to="/products">Explore products</Link></div>}</div></main>
}