import { ArrowRight, Headphones, Laptop, ShieldCheck, Smartphone, Truck, Watch } from 'lucide-react'
import { Link } from 'react-router-dom'
import { categories, products } from '../data/products'
import ProductCard from '../components/ProductCard'
import Claculate from '../components/Claculate'

export default function Home({ onAddToCart, onToggleFavorite, favorites }) {
  const featuredProducts = products.slice(0, 4)
  const categoryIcons = { Smartphones: Smartphone, Laptops: Laptop, Audio: Headphones, Wearables: Watch }
  return <main>
    <section className="hero"><div className="container hero-inner"><div className="hero-copy"><p className="eyebrow">THE FUTURE, CURATED</p><h1>Good tech.<br /><em>Better living.</em></h1><p className="hero-description">Thoughtfully selected technology for the way you work, play, and connect.</p><Link className="button button-dark" to="/products">Explore the collection <ArrowRight size={17} /></Link><div className="hero-proof"><span>4.9/5</span><span className="stars">★★★★★</span><span>from 2,000+ happy customers</span></div></div><div className="hero-visual"><div className="hero-orbit orbit-one"></div><div className="hero-orbit orbit-two"></div><img src="https://cdn.prod.website-files.com/61a5e47b1afd0c116d16aa40/69faf4d31de66816e9aef2af_Frame%202087327708.png" alt="Laptop and smartphone on a desk" /><div className="hero-tag"><span>01</span><span>Make space<br />for better ideas.</span></div></div></div></section>
    <section className="section container"><div className="section-heading"><div><p className="eyebrow">SHOP BY CATEGORY</p><h2>Find your next favorite.</h2></div><Link className="text-link" to="/products">View all <ArrowRight size={16} /></Link></div><div className="category-grid">{categories.map((category) => { const Icon = categoryIcons[category.name] || Smartphone; return <Link className="category-card" to={`/products?category=${category.name}`} key={category.id}><img src={category.image} alt={category.name} /><div className="category-overlay"><Icon size={20} /><h3>{category.name}</h3><span>{category.description}</span></div></Link> })}</div></section>
    <section className="section featured-section"><div className="container"><div className="section-heading"><div><p className="eyebrow">THE SHORTLIST</p><h2>Popular right now.</h2></div><Link className="text-link" to="/products">Shop all products <ArrowRight size={16} /></Link></div><div className="product-grid">{featuredProducts.map((product) => <ProductCard key={product.id} product={product} onAddToCart={onAddToCart} onToggleFavorite={onToggleFavorite} isFavorite={favorites.includes(product.id)} />)}</div></div></section>
    <section className="why-section" id="why-us"><div className="container why-grid"><div><p className="eyebrow">WHY TECHMARKET</p><h2>Good products.<br /><em>Good practice.</em></h2></div><div className="feature-list"><div><Truck /><span><strong>Fast, careful delivery</strong><small>Free shipping over $75, always tracked.</small></span></div><div><ShieldCheck /><span><strong>Quality, guaranteed</strong><small>Every product is checked and backed by us.</small></span></div><div><Headphones /><span><strong>Real human support</strong><small>Friendly advice from people who know tech.</small></span></div></div></div></section>
  </main>
}