import { ArrowRight, Calculator, Headphones, Laptop, ShieldCheck, Smartphone, Truck, Watch, X } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useState } from 'react'
import { categories, products } from '../data/products'
import ProductCard from '../components/ProductCard'
import Claculate from '../components/Claculate'

export default function Home({ onAddToCart, onToggleFavorite, favorites }) {
  const [calculatorOpen, setCalculatorOpen] = useState(false)
  const featuredProducts = products.slice(0, 4)
  const categoryIcons = { Smartphones: Smartphone, Laptops: Laptop, Audio: Headphones, Wearables: Watch }
  return <main className="home-page">
    <section className="hero"><div className="container hero-inner"><div className="hero-copy"><p className="eyebrow">TECHMARKET / FIELD NOTE 001</p><h1>Objects<br /><em>with intent.</em></h1><p className="hero-description">A living index of the tools that make ordinary days feel more capable.</p><div className="hero-actions"><Link className="button button-dark" to="/products">Enter the archive <ArrowRight size={17} /></Link><span className="hero-code">SCAN_09<br /><strong>ONLINE</strong></span></div><div className="hero-proof"><span>4.9/5</span><span className="stars">★★★★★</span><span>verified by 2,000+ users</span></div></div><div className="hero-visual"><div className="visual-label label-top">CURATED<br />HARDWARE</div><div className="hero-orbit orbit-one"></div><div className="hero-orbit orbit-two"></div><div className="hero-image-frame"><img src="https://cdn.prod.website-files.com/61a5e47b1afd0c116d16aa40/69faf4d31de66816e9aef2af_Frame%202087327708.png" alt="Laptop and smartphone on a desk" /><span className="image-crosshair">+</span></div><div className="hero-tag"><span>01</span><span>Make space<br />for better ideas.</span></div><div className="visual-label label-bottom">LAT 40.71<br />LONG 74.00</div></div></div></section>
    <section className="signal-strip"><div className="container signal-grid"><span>LIVE INDEX</span><strong>08</strong><span>OBJECTS IN ROTATION</span><i></i><span>LAST SYNC / 09.13.26</span><Link to="/products">OPEN CATALOG <ArrowRight size={14} /></Link></div></section>
    <section className="section container home-categories"><div className="section-heading"><div><p className="eyebrow">01 / NAVIGATE</p><h2>Find your next favorite.</h2></div><Link className="text-link" to="/products">View all <ArrowRight size={16} /></Link></div><div className="category-grid">{categories.map((category, index) => { const Icon = categoryIcons[category.name] || Smartphone; return <Link className="category-card" to={`/products?category=${category.name}`} key={category.id}><span className="category-index">0{index + 1}</span><img src={category.image} alt={category.name} /><div className="category-overlay"><Icon size={20} /><h3>{category.name}</h3><span>{category.description}</span></div></Link> })}<button className={`category-card calculator-category ${calculatorOpen ? 'is-open' : ''}`} onClick={() => setCalculatorOpen((open) => !open)} aria-expanded={calculatorOpen}><span className="category-index">06</span>{calculatorOpen ? <div className="category-calculator"><div className="category-calculator-head"><span>QUICK CALC / ONLINE</span><X size={17} /></div><Claculate /></div> : <div className="category-overlay"><Calculator size={20} /><h3>Calculator</h3><span>Run the numbers before you choose.</span></div>}</button></div></section>
    <section className="section featured-section"><div className="container"><div className="section-heading"><div><p className="eyebrow">THE SHORTLIST</p><h2>Popular right now.</h2></div><Link className="text-link" to="/products">Shop all products <ArrowRight size={16} /></Link></div><div className="product-grid">{featuredProducts.map((product) => <ProductCard key={product.id} product={product} onAddToCart={onAddToCart} onToggleFavorite={onToggleFavorite} isFavorite={favorites.includes(product.id)} />)}</div></div></section>
    <section className="why-section" id="why-us"><div className="container why-grid"><div className="why-intro"><p className="eyebrow">02 / THE PROTOCOL</p><h2>Good products.<br /><em>Good practice.</em></h2><p className="why-note">We keep the signal clean: fewer objects, better decisions, and support that stays human.</p><div className="why-readout"><span>TRUST INDEX</span><strong>98.4</strong><small>/ 100</small></div></div><div className="feature-list"><div><span className="feature-number">01</span><Truck /><span><strong>Fast, careful delivery</strong><small>Free shipping over $75, always tracked.</small></span></div><div><span className="feature-number">02</span><ShieldCheck /><span><strong>Quality, guaranteed</strong><small>Every product is checked and backed by us.</small></span></div><div><span className="feature-number">03</span><Headphones /><span><strong>Real human support</strong><small>Friendly advice from people who know tech.</small></span></div></div></div><div className="container why-signal"><span>PROTOCOL ACTIVE</span><i></i><span>NO HIDDEN FEES</span><i></i><span>30 DAY RETURNS</span><i></i><span>HUMAN VERIFIED</span></div></section>
  </main>
}